# Generated by Django 2.2.3 on 2019-07-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_person_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Location',
        ),
    ]
